### PR TITLE
Showcase specification

### PR DESCRIPTION
**Pull request by brew**
This Pull Request refers to issue #64.

Please use this Pull Request for discussion related to the new CKAN 'Showcase' feature (aka, Related Items). **DO NOT MERGE** until the spec has settled (likely when the feature is released).

### CODE REVIEW

**Comment by rossjones** [comment]
@brew Is this ready to be merged?

**Comment by brew** [comment]
@rossjones Sorry, I've been away at a conference, but I saw your discussion with @wardi about using github issues/prs as a discussion mechanism for new features on irc.

I found this method of soliciting feedback for the spec very useful. It allowed interested parties to contribute their view using familiar tools. The spec itself is versioned, and changes made in response to the discussion can be tracked. Also people can subscribe to the discussion and be notified etc. So, the initial idea is proposed as an issue (in this example #64) in the ideas and roadmap repository, then fleshed out further here as a PR with a spec document and supporting material once someone decides to take it on.

@wardi [said](https://botbot.me/freenode/ckan/2015-03-09/?msg=33720893&page=1): 

> the pep process might need a benevolant dictator to make work well, otherwise they can just get pulled in every direction

In this particular case, I was the one making changes to the spec in response to the discussion, deciding what to take and what to leave. It doesn't have to be the implementor, but I would suggest that committing changes based on the discussion should be restricted to someone close to the implementation (like the implementor or product manager/owner).

It's usefulness is in the discussion around the PR, so there isn't a definite point when it needs to be merged. Perhaps once the feature is released would be a good time? Then, if the feature doesn't progress beyond the PR discussion, it just remains unmerged. 

In this case, the [ckanext-showcase](https://github.com/ckan/ckanext-showcase/) extension is being actively worked on, and will hopefully be ready for testing soon.

**Comment by brew** [comment]
This can be merged now, as Showcase has been released and in active use for a little while. Would someone else like to pull the trigger? @amercader, @rossjones, @wardi ?

**Comment by amercader** [comment]
Great work @brew

**Pull request merged**
